from .de import (
    compress_de_axis_to_sp,
    compress_de_to_sp_with_ax_loc,
    compress_de_to_sp_with_ax_mask,
    compress_de_coos_to_sp,
    compress_de_to_sp_with_coo_loc,
    compress_de_to_sp_with_coo_mask,
    compress_de_axis,
    compress_de_with_ax_loc,
    compress_de_with_ax_mask,
    compress_de_with_ax_slice,
    compress_de_axes,
    compress_de_with_box_loc,
    compress_de_with_box_mask,
    compress_de_with_box_slice,
    compress_de_coos,
    compress_de_with_coo_loc,
    compress_de_with_coo_mask,
)
from .sp import compress_sp_axis, compress_sp_axes
